export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
export const FETCH_TODOS_SUCCESS= 'FETCH_TODOS_SUCCESS';;
export const FETCH_TODOS_FAIL= 'FETCH_TODOS_FAIL';

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';